CREATE TABLE PLATAFORMA(
IDPLATAFORMA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOME VARCHAR(50)
);

CREATE TABLE GENERO(
IDGENERO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NOME VARCHAR(50)
);

CREATE TABLE JOGOS(
IDJOGO INT PRIMARY KEY auto_increment NOT NULL,
NOME VARCHAR(50)
);


ALTER TABLE JOGOS ADD foreign key (FKIDPLATAFORMA)references PLATAFORMA(IDPLATAFORMA)
FOREIGN KEY (FKIDGENERO) REFERENCES GENERO(IDGENERO)
FKIDPLATAFORMA INT

FKIDGENERO INT




FKIDPLATAFORMA INT,
CONSTRAINT FKIDGENERO FOREIGN KEY (FKIDGENERO) REFERENCES GENERO(IDGENERO),
CONSTRAINT FKIDPLATAFORMA foreign key (FKIDPLATAFORMA)references PLATAFORMA(IDPLATAFORMA)


DESCRIBE JOGOS


